import { TennisEquipment } from "@/types";

// In-memory data store (in a real app, this would be a database)
let equipmentStore: TennisEquipment[] = [
  {
    id: "1",
    title: "Wilson Pro Staff RF97",
    description:
      "Excellent condition tennis racket, barely used. Perfect for intermediate to advanced players.",
    category: "racket",
    condition: "like-new",
    price: 150,
    brand: "Wilson",
    sellerName: "Nikhil Naidu",
    sellerEmail: "nikhil@example.com",
    sellerPhone: "+918652051714",
    location: "Mumbai, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
      "https://images.unsplash.com/photo-1617083278066-d6be49c6a6f8?w=800&q=80",
    ],
    createdAt: new Date("2024-10-15").toISOString(),
  },
  {
    id: "2",
    title: "Nike Court Air Zoom Vapor Pro",
    description: "Professional tennis shoes, size 10. Worn only a few times.",
    category: "shoes",
    condition: "good",
    price: 80,
    brand: "Nike",
    sellerName: "Vinayak Garudi",
    sellerEmail: "vinayak@example.com",
    sellerPhone: "+918652051715",
    location: "Delhi, India",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    createdAt: new Date("2024-10-18").toISOString(),
  },
  {
    id: "3",
    title: "Head Tour Team Backpack",
    description:
      "Spacious tennis bag with multiple compartments. Great for tournaments.",
    category: "bag",
    condition: "good",
    price: 60,
    brand: "Head",
    sellerName: "Pravin Natsu",
    sellerEmail: "pravin@example.com",
    sellerPhone: "+918652051715",
    location: "Bangalore, India",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
      "https://images.unsplash.com/photo-1491637639811-60e2756cc1c7?w=800&q=80",
      "https://images.unsplash.com/photo-1547949003-9792a18a2601?w=800&q=80",
    ],
    createdAt: new Date("2024-10-20").toISOString(),
  },
  {
    id: "4",
    title: "Babolat Pure Drive 2023",
    description:
      "Latest model tennis racket, lightly used. Includes original cover.",
    category: "racket",
    condition: "like-new",
    price: 180,
    brand: "Babolat",
    sellerName: "Rahul Sharma",
    sellerEmail: "rahul@example.com",
    sellerPhone: "+918652051716",
    location: "Pune, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-19").toISOString(),
  },
  {
    id: "5",
    title: "Adidas Barricade Tennis Shoes",
    description: "Durable tennis shoes, size 9. Great grip and support.",
    category: "shoes",
    condition: "good",
    price: 70,
    brand: "Adidas",
    sellerName: "Priya Singh",
    sellerEmail: "priya@example.com",
    sellerPhone: "+918652051717",
    location: "Chennai, India",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    createdAt: new Date("2024-10-17").toISOString(),
  },
  {
    id: "6",
    title: "Wilson Tennis Ball Set",
    description: "Pack of 12 tennis balls. Perfect for practice sessions.",
    category: "balls",
    condition: "like-new",
    price: 25,
    brand: "Wilson",
    sellerName: "Amit Kumar",
    sellerEmail: "amit@example.com",
    sellerPhone: "+918652051718",
    location: "Kolkata, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-16").toISOString(),
  },
  {
    id: "7",
    title: "Yonex Tennis Bag Pro Series",
    description:
      "Professional tennis bag with shoe compartment. Excellent condition.",
    category: "bag",
    condition: "like-new",
    price: 85,
    brand: "Yonex",
    sellerName: "Neha Patel",
    sellerEmail: "neha@example.com",
    sellerPhone: "+918652051719",
    location: "Ahmedabad, India",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    createdAt: new Date("2024-10-14").toISOString(),
  },
  {
    id: "8",
    title: "Prince Textreme Beast 100",
    description: "Power racket for aggressive players. Used for 3 months.",
    category: "racket",
    condition: "good",
    price: 140,
    brand: "Prince",
    sellerName: "Arjun Reddy",
    sellerEmail: "arjun@example.com",
    sellerPhone: "+918652051720",
    location: "Hyderabad, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-13").toISOString(),
  },
  {
    id: "9",
    title: "Nike Tennis Visor",
    description: "Lightweight visor for sun protection. Brand new with tags.",
    category: "accessories",
    condition: "like-new",
    price: 20,
    brand: "Nike",
    sellerName: "Simran Kaur",
    sellerEmail: "simran@example.com",
    sellerPhone: "+918652051721",
    location: "Chandigarh, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-12").toISOString(),
  },
  {
    id: "10",
    title: "Under Armour Tennis Shorts",
    description: "Comfortable tennis shorts, size M. Worn a few times.",
    category: "apparel",
    condition: "good",
    price: 30,
    brand: "Under Armour",
    sellerName: "Vikram Malhotra",
    sellerEmail: "vikram@example.com",
    sellerPhone: "+918652051722",
    location: "Jaipur, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-11").toISOString(),
  },
  {
    id: "11",
    title: "Head Graphene 360+ Extreme",
    description: "Advanced racket with excellent spin potential. Barely used.",
    category: "racket",
    condition: "like-new",
    price: 190,
    brand: "Head",
    sellerName: "Ravi Verma",
    sellerEmail: "ravi@example.com",
    sellerPhone: "+918652051723",
    location: "Lucknow, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-10").toISOString(),
  },
  {
    id: "12",
    title: "Asics Gel-Resolution 8",
    description: "Top-tier tennis shoes with amazing comfort. Size 10.5.",
    category: "shoes",
    condition: "good",
    price: 95,
    brand: "Asics",
    sellerEmail: "meera@example.com",
    sellerPhone: "+918652051724",
    location: "Indore, India",
    sellerName: "Meera Joshi",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    createdAt: new Date("2024-10-09").toISOString(),
  },
  {
    id: "13",
    title: "Penn Championship Tennis Balls",
    description: "Professional grade tennis balls. Pack of 18.",
    category: "balls",
    condition: "like-new",
    price: 35,
    brand: "Penn",
    sellerName: "Karan Mehta",
    sellerEmail: "karan@example.com",
    sellerPhone: "+918652051725",
    location: "Surat, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-08").toISOString(),
  },
  {
    id: "14",
    title: "Wilson Federer DNA Backpack",
    description: "Stylish tennis backpack with multiple pockets.",
    category: "bag",
    condition: "good",
    price: 75,
    brand: "Wilson",
    sellerName: "Anjali Desai",
    sellerEmail: "anjali@example.com",
    sellerPhone: "+918652051726",
    location: "Vadodara, India",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    createdAt: new Date("2024-10-07").toISOString(),
  },
  {
    id: "15",
    title: "Dunlop CX 200 Tour",
    description: "Control-oriented racket for advanced players.",
    category: "racket",
    condition: "good",
    price: 160,
    brand: "Dunlop",
    sellerName: "Sanjay Gupta",
    sellerEmail: "sanjay@example.com",
    sellerPhone: "+918652051727",
    location: "Nagpur, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-06").toISOString(),
  },
  {
    id: "16",
    title: "Adidas Tennis Wristbands",
    description: "Set of 4 wristbands. Moisture-wicking material.",
    category: "accessories",
    condition: "like-new",
    price: 15,
    brand: "Adidas",
    sellerName: "Pooja Rao",
    sellerEmail: "pooja@example.com",
    sellerPhone: "+918652051728",
    location: "Visakhapatnam, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-05").toISOString(),
  },
  {
    id: "17",
    title: "Nike Court Dri-FIT T-Shirt",
    description: "Breathable tennis t-shirt, size L. Excellent condition.",
    category: "apparel",
    condition: "like-new",
    price: 35,
    brand: "Nike",
    sellerName: "Rohit Nair",
    sellerEmail: "rohit@example.com",
    sellerPhone: "+918652051729",
    location: "Kochi, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-04").toISOString(),
  },
  {
    id: "18",
    title: "Tecnifibre TFight 305",
    description: "All-around racket with great feel. Used occasionally.",
    category: "racket",
    condition: "good",
    price: 145,
    brand: "Tecnifibre",
    sellerName: "Deepak Singh",
    sellerEmail: "deepak@example.com",
    sellerPhone: "+918652051730",
    location: "Bhopal, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-03").toISOString(),
  },
  {
    id: "19",
    title: "K-Swiss Hypercourt Express",
    description: "Lightweight tennis shoes, size 9.5. Minimal wear.",
    category: "shoes",
    condition: "like-new",
    price: 85,
    brand: "K-Swiss",
    sellerName: "Kavya Iyer",
    sellerEmail: "kavya@example.com",
    sellerPhone: "+918652051731",
    location: "Coimbatore, India",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    createdAt: new Date("2024-10-02").toISOString(),
  },
  {
    id: "20",
    title: "Slazenger Wimbledon Tennis Balls",
    description: "Official Wimbledon balls. Pack of 12.",
    category: "balls",
    condition: "like-new",
    price: 40,
    brand: "Slazenger",
    sellerName: "Aditya Kapoor",
    sellerEmail: "aditya@example.com",
    sellerPhone: "+918652051732",
    location: "Gurgaon, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-10-01").toISOString(),
  },
  {
    id: "21",
    title: "Babolat Team Line Duffle Bag",
    description: "Large duffle bag for tennis gear. Like new condition.",
    category: "bag",
    condition: "like-new",
    price: 90,
    brand: "Babolat",
    sellerName: "Ishaan Chopra",
    sellerEmail: "ishaan@example.com",
    sellerPhone: "+918652051733",
    location: "Noida, India",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    createdAt: new Date("2024-09-30").toISOString(),
  },
  {
    id: "22",
    title: "Wilson Blade 98 16x19",
    description: "Perfect for control players. String recently replaced.",
    category: "racket",
    condition: "good",
    price: 155,
    brand: "Wilson",
    sellerName: "Tanya Saxena",
    sellerEmail: "tanya@example.com",
    sellerPhone: "+918652051734",
    location: "Faridabad, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-29").toISOString(),
  },
  {
    id: "23",
    title: "New Balance 996v4 Tennis Shoes",
    description: "Stability-focused tennis shoes, size 11.",
    category: "shoes",
    condition: "good",
    price: 80,
    brand: "New Balance",
    sellerName: "Manish Tiwari",
    sellerEmail: "manish@example.com",
    sellerPhone: "+918652051735",
    location: "Ghaziabad, India",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    createdAt: new Date("2024-09-28").toISOString(),
  },
  {
    id: "24",
    title: "HEAD Tennis Cap",
    description: "Adjustable tennis cap with UV protection.",
    category: "accessories",
    condition: "like-new",
    price: 18,
    brand: "Head",
    sellerName: "Shruti Kulkarni",
    sellerEmail: "shruti@example.com",
    sellerPhone: "+918652051736",
    location: "Nashik, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-27").toISOString(),
  },
  {
    id: "25",
    title: "Adidas Tennis Skirt",
    description: "Comfortable tennis skirt, size S. Built-in shorts.",
    category: "apparel",
    condition: "like-new",
    price: 40,
    brand: "Adidas",
    sellerName: "Nidhi Agarwal",
    sellerEmail: "nidhi@example.com",
    sellerPhone: "+918652051737",
    location: "Meerut, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-26").toISOString(),
  },
  {
    id: "26",
    title: "Yonex EZONE 98",
    description: "Modern player racket with excellent feel and power.",
    category: "racket",
    condition: "like-new",
    price: 175,
    brand: "Yonex",
    sellerName: "Gaurav Bhatia",
    sellerEmail: "gaurav@example.com",
    sellerPhone: "+918652051738",
    location: "Ludhiana, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-25").toISOString(),
  },
  {
    id: "27",
    title: "Dunlop Fort Elite Tennis Balls",
    description: "High-quality tournament balls. Pack of 24.",
    category: "balls",
    condition: "like-new",
    price: 50,
    brand: "Dunlop",
    sellerName: "Sneha Menon",
    sellerEmail: "sneha@example.com",
    sellerPhone: "+918652051739",
    location: "Thiruvananthapuram, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-24").toISOString(),
  },
  {
    id: "28",
    title: "Prince Team 6 Pack Bag",
    description: "Holds up to 6 rackets. Multiple storage compartments.",
    category: "bag",
    condition: "good",
    price: 70,
    brand: "Prince",
    sellerName: "Varun Khanna",
    sellerEmail: "varun@example.com",
    sellerPhone: "+918652051740",
    location: "Amritsar, India",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    createdAt: new Date("2024-09-23").toISOString(),
  },
  {
    id: "29",
    title: "Babolat Pure Aero 2022",
    description: "Rafael Nadal racket. Excellent for spin generation.",
    category: "racket",
    condition: "good",
    price: 165,
    brand: "Babolat",
    sellerName: "Ritika Sethi",
    sellerEmail: "ritika@example.com",
    sellerPhone: "+918652051741",
    location: "Jalandhar, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-22").toISOString(),
  },
  {
    id: "30",
    title: "Puma Fuse Tennis Shoes",
    description: "Modern design tennis shoes, size 10. Great condition.",
    category: "shoes",
    condition: "like-new",
    price: 75,
    brand: "Puma",
    sellerName: "Harshit Pandey",
    sellerEmail: "harshit@example.com",
    sellerPhone: "+918652051742",
    location: "Kanpur, India",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    createdAt: new Date("2024-09-21").toISOString(),
  },
  {
    id: "31",
    title: "Wilson String Dampener Pack",
    description: "Pack of 10 vibration dampeners. Various colors.",
    category: "accessories",
    condition: "like-new",
    price: 12,
    brand: "Wilson",
    sellerName: "Divya Chauhan",
    sellerEmail: "divya@example.com",
    sellerPhone: "+918652051743",
    location: "Agra, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-20").toISOString(),
  },
  {
    id: "32",
    title: "Lacoste Tennis Polo",
    description: "Classic tennis polo shirt, size M. Barely worn.",
    category: "apparel",
    condition: "like-new",
    price: 55,
    brand: "Lacoste",
    sellerName: "Sahil Malik",
    sellerEmail: "sahil@example.com",
    sellerPhone: "+918652051744",
    location: "Jodhpur, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-19").toISOString(),
  },
  {
    id: "33",
    title: "Head Radical MP 2023",
    description: "Versatile racket suitable for all-court players.",
    category: "racket",
    condition: "like-new",
    price: 185,
    brand: "Head",
    sellerName: "Ananya Dubey",
    sellerEmail: "ananya@example.com",
    sellerPhone: "+918652051745",
    location: "Ranchi, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-18").toISOString(),
  },
  {
    id: "34",
    title: "Mizuno Wave Exceed Tour",
    description: "High-performance tennis shoes, size 9. Excellent cushioning.",
    category: "shoes",
    condition: "good",
    price: 90,
    brand: "Mizuno",
    sellerName: "Kunal Jain",
    sellerEmail: "kunal@example.com",
    sellerPhone: "+918652051746",
    location: "Raipur, India",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    createdAt: new Date("2024-09-17").toISOString(),
  },
  {
    id: "35",
    title: "Tretorn Micro X Tennis Balls",
    description: "Pressureless tennis balls. Pack of 18. Last longer.",
    category: "balls",
    condition: "like-new",
    price: 45,
    brand: "Tretorn",
    sellerName: "Megha Reddy",
    sellerEmail: "megha@example.com",
    sellerPhone: "+918652051747",
    location: "Vijayawada, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-16").toISOString(),
  },
  {
    id: "36",
    title: "Tecnifibre Endurance Racket Bag",
    description: "Thermal bag for 9 rackets. Excellent protection.",
    category: "bag",
    condition: "like-new",
    price: 95,
    brand: "Tecnifibre",
    sellerName: "Naveen Kumar",
    sellerEmail: "naveen@example.com",
    sellerPhone: "+918652051748",
    location: "Mysore, India",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    createdAt: new Date("2024-09-15").toISOString(),
  },
  {
    id: "37",
    title: "Wilson Ultra 100 V4",
    description: "Power racket with modern design. Used for 2 months.",
    category: "racket",
    condition: "good",
    price: 170,
    brand: "Wilson",
    sellerName: "Pallavi Shah",
    sellerEmail: "pallavi@example.com",
    sellerPhone: "+918652051749",
    location: "Rajkot, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-14").toISOString(),
  },
  {
    id: "38",
    title: "Nike Tennis Headband",
    description: "Sweat-wicking headband. Pack of 3 different colors.",
    category: "accessories",
    condition: "like-new",
    price: 18,
    brand: "Nike",
    sellerName: "Tarun Ahuja",
    sellerEmail: "tarun@example.com",
    sellerPhone: "+918652051750",
    location: "Aurangabad, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-13").toISOString(),
  },
  {
    id: "39",
    title: "Fila Tennis Track Pants",
    description: "Comfortable track pants for tennis, size L.",
    category: "apparel",
    condition: "good",
    price: 38,
    brand: "Fila",
    sellerName: "Ria Banerjee",
    sellerEmail: "ria@example.com",
    sellerPhone: "+918652051751",
    location: "Siliguri, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-12").toISOString(),
  },
  {
    id: "40",
    title: "Dunlop SX 300 Tour",
    description: "Advanced racket for tournament players. Well maintained.",
    category: "racket",
    condition: "good",
    price: 150,
    brand: "Dunlop",
    sellerName: "Akash Sinha",
    sellerEmail: "akash@example.com",
    sellerPhone: "+918652051752",
    location: "Patna, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-11").toISOString(),
  },
  {
    id: "41",
    title: "Diadora Speed Blushield",
    description: "Italian-made tennis shoes, size 10.5. Premium quality.",
    category: "shoes",
    condition: "like-new",
    price: 100,
    brand: "Diadora",
    sellerName: "Sonali Ghosh",
    sellerEmail: "sonali@example.com",
    sellerPhone: "+918652051753",
    location: "Durgapur, India",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    createdAt: new Date("2024-09-10").toISOString(),
  },
  {
    id: "42",
    title: "Babolat Gold Championship Balls",
    description: "Tournament-grade tennis balls. Pack of 12.",
    category: "balls",
    condition: "like-new",
    price: 38,
    brand: "Babolat",
    sellerName: "Yash Goyal",
    sellerEmail: "yash@example.com",
    sellerPhone: "+918652051754",
    location: "Udaipur, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-09").toISOString(),
  },
  {
    id: "43",
    title: "Yonex Pro Racquet Bag",
    description: "Professional racket bag with thermal protection.",
    category: "bag",
    condition: "good",
    price: 80,
    brand: "Yonex",
    sellerName: "Kritika Sharma",
    sellerEmail: "kritika@example.com",
    sellerPhone: "+918652051755",
    location: "Dehradun, India",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    createdAt: new Date("2024-09-08").toISOString(),
  },
  {
    id: "44",
    title: "Prince Warrior 100",
    description: "Arm-friendly racket with good power. Excellent condition.",
    category: "racket",
    condition: "like-new",
    price: 135,
    brand: "Prince",
    sellerName: "Mohit Arora",
    sellerEmail: "mohit@example.com",
    sellerPhone: "+918652051756",
    location: "Shimla, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-07").toISOString(),
  },
  {
    id: "45",
    title: "Adidas Tennis Socks",
    description: "Pack of 6 pairs. Cushioned tennis socks.",
    category: "accessories",
    condition: "like-new",
    price: 22,
    brand: "Adidas",
    sellerName: "Sakshi Verma",
    sellerEmail: "sakshi@example.com",
    sellerPhone: "+918652051757",
    location: "Guwahati, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-06").toISOString(),
  },
  {
    id: "46",
    title: "Sergio Tacchini Tennis Jacket",
    description: "Classic tennis jacket, size XL. Vintage style.",
    category: "apparel",
    condition: "good",
    price: 50,
    brand: "Sergio Tacchini",
    sellerName: "Vishal Gupta",
    sellerEmail: "vishal@example.com",
    sellerPhone: "+918652051758",
    location: "Bhubaneswar, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-05").toISOString(),
  },
  {
    id: "47",
    title: "Tecnifibre TFight 315",
    description: "Heavier version for baseline players. Great stability.",
    category: "racket",
    condition: "good",
    price: 155,
    brand: "Tecnifibre",
    sellerName: "Preeti Jha",
    sellerEmail: "preeti@example.com",
    sellerPhone: "+918652051759",
    location: "Cuttack, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-04").toISOString(),
  },
  {
    id: "48",
    title: "Lotto Raptor Ultra",
    description: "Lightweight tennis shoes, size 9.5. Italian design.",
    category: "shoes",
    condition: "good",
    price: 65,
    brand: "Lotto",
    sellerName: "Abhishek Das",
    sellerEmail: "abhishek@example.com",
    sellerPhone: "+918652051760",
    location: "Jammu, India",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    createdAt: new Date("2024-09-03").toISOString(),
  },
  {
    id: "49",
    title: "Wilson US Open Tennis Balls",
    description: "Official US Open balls. Pack of 18.",
    category: "balls",
    condition: "like-new",
    price: 48,
    brand: "Wilson",
    sellerName: "Rachna Singh",
    sellerEmail: "rachna@example.com",
    sellerPhone: "+918652051761",
    location: "Srinagar, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-09-02").toISOString(),
  },
  {
    id: "50",
    title: "Head Tour Team Supercombi",
    description: "Compact bag for essentials. Perfect for club play.",
    category: "bag",
    condition: "like-new",
    price: 55,
    brand: "Head",
    sellerName: "Nitin Pandey",
    sellerEmail: "nitin@example.com",
    sellerPhone: "+918652051762",
    location: "Panaji, India",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    createdAt: new Date("2024-09-01").toISOString(),
  },
  {
    id: "51",
    title: "Babolat Pure Strike 98",
    description: "Precision racket for advanced players. Recently restrung.",
    category: "racket",
    condition: "good",
    price: 172,
    brand: "Babolat",
    sellerName: "Swati Mishra",
    sellerEmail: "swati@example.com",
    sellerPhone: "+918652051763",
    location: "Imphal, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-08-31").toISOString(),
  },
  {
    id: "52",
    title: "Wilson Tennis Grip Tape",
    description: "Pack of 12 overgrips. Various colors available.",
    category: "accessories",
    condition: "like-new",
    price: 25,
    brand: "Wilson",
    sellerName: "Karthik Nair",
    sellerEmail: "karthik@example.com",
    sellerPhone: "+918652051764",
    location: "Kottayam, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-08-30").toISOString(),
  },
  {
    id: "53",
    title: "Reebok Tennis Dress",
    description: "Sporty tennis dress, size M. Built-in bra support.",
    category: "apparel",
    condition: "like-new",
    price: 45,
    brand: "Reebok",
    sellerName: "Tanvi Kapoor",
    sellerEmail: "tanvi@example.com",
    sellerPhone: "+918652051765",
    location: "Mangalore, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-08-29").toISOString(),
  },
  {
    id: "54",
    title: "Yonex VCore 98",
    description: "Spin-friendly racket with excellent control.",
    category: "racket",
    condition: "like-new",
    price: 180,
    brand: "Yonex",
    sellerName: "Raghav Malhotra",
    sellerEmail: "raghav@example.com",
    sellerPhone: "+918652051766",
    location: "Madurai, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-08-28").toISOString(),
  },
  {
    id: "55",
    title: "Fila Axilus 2 Energized",
    description: "Energetic tennis shoes, size 10. Maximum comfort.",
    category: "shoes",
    condition: "good",
    price: 78,
    brand: "Fila",
    sellerName: "Bhavna Roy",
    sellerEmail: "bhavna@example.com",
    sellerPhone: "+918652051767",
    location: "Trichy, India",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    createdAt: new Date("2024-08-27").toISOString(),
  },
  {
    id: "56",
    title: "Head ATP Golden Balls",
    description: "Premium tennis balls used in ATP tournaments. Pack of 12.",
    category: "balls",
    condition: "like-new",
    price: 42,
    brand: "Head",
    sellerName: "Chirag Patel",
    sellerEmail: "chirag@example.com",
    sellerPhone: "+918652051768",
    location: "Salem, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-08-26").toISOString(),
  },
  {
    id: "57",
    title: "Wilson Roland Garros Team Bag",
    description: "Limited edition bag from French Open. 6 racket capacity.",
    category: "bag",
    condition: "like-new",
    price: 88,
    brand: "Wilson",
    sellerName: "Diya Sharma",
    sellerEmail: "diya@example.com",
    sellerPhone: "+918652051769",
    location: "Tirupati, India",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    createdAt: new Date("2024-08-25").toISOString(),
  },
  {
    id: "58",
    title: "Dunlop Biomimetic M3.0",
    description: "Versatile racket for intermediate players. Good condition.",
    category: "racket",
    condition: "good",
    price: 125,
    brand: "Dunlop",
    sellerName: "Ayush Kumar",
    sellerEmail: "ayush@example.com",
    sellerPhone: "+918652051770",
    location: "Warangal, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-08-24").toISOString(),
  },
  {
    id: "59",
    title: "Babolat Tennis Elbow Support",
    description: "Compression sleeve for tennis elbow. Size L.",
    category: "accessories",
    condition: "like-new",
    price: 28,
    brand: "Babolat",
    sellerName: "Lakshmi Iyer",
    sellerEmail: "lakshmi@example.com",
    sellerPhone: "+918652051771",
    location: "Guntur, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-08-23").toISOString(),
  },
  {
    id: "60",
    title: "Ellesse Tennis Hoodie",
    description: "Warm-up hoodie for tennis, size L. Classic design.",
    category: "apparel",
    condition: "good",
    price: 48,
    brand: "Ellesse",
    sellerName: "Siddharth Reddy",
    sellerEmail: "siddharth@example.com",
    sellerPhone: "+918652051772",
    location: "Kakinada, India",
    images: [
      "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&q=80",
    ],
    createdAt: new Date("2024-08-22").toISOString(),
  },
];

export function getAllEquipment(): TennisEquipment[] {
  return [...equipmentStore].sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  );
}

export function addEquipment(
  equipment: Omit<TennisEquipment, "id" | "createdAt">
): TennisEquipment {
  const newEquipment: TennisEquipment = {
    ...equipment,
    id: Date.now().toString(),
    createdAt: new Date().toISOString(),
  };
  equipmentStore.push(newEquipment);
  return newEquipment;
}

export function filterEquipment(filters: {
  category?: string;
  condition?: string;
  minPrice?: number;
  maxPrice?: number;
  search?: string;
}): TennisEquipment[] {
  let filtered = getAllEquipment();

  if (filters.category && filters.category !== "all") {
    filtered = filtered.filter((item) => item.category === filters.category);
  }

  if (filters.condition && filters.condition !== "all") {
    filtered = filtered.filter((item) => item.condition === filters.condition);
  }

  if (filters.minPrice !== undefined) {
    filtered = filtered.filter((item) => item.price >= filters.minPrice!);
  }

  if (filters.maxPrice !== undefined) {
    filtered = filtered.filter((item) => item.price <= filters.maxPrice!);
  }

  if (filters.search) {
    const searchLower = filters.search.toLowerCase();
    filtered = filtered.filter(
      (item) =>
        item.title.toLowerCase().includes(searchLower) ||
        item.description.toLowerCase().includes(searchLower) ||
        item.brand?.toLowerCase().includes(searchLower) ||
        item.location.toLowerCase().includes(searchLower)
    );
  }

  return filtered;
}

export function paginateEquipment(
  filters: {
    category?: string;
    condition?: string;
    minPrice?: number;
    maxPrice?: number;
    search?: string;
  },
  page: number = 1,
  pageSize: number = 10
): { items: TennisEquipment[]; total: number; hasMore: boolean } {
  const allFiltered = filterEquipment(filters);
  const startIndex = (page - 1) * pageSize;
  const endIndex = startIndex + pageSize;
  const items = allFiltered.slice(startIndex, endIndex);

  return {
    items,
    total: allFiltered.length,
    hasMore: endIndex < allFiltered.length,
  };
}
